
name: Build and Push Woodgrove Image

on:
  push:
    branches: [ "eyalsofer/woodgrove" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

env:
  REGISTRY: c2cplayground.azurecr.io
  IMAGE_NAME: woodgrove-app-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout woodgrove repo
        uses: actions/checkout@v4
        with:
          repository: build25-woodgrove/mdc-playbook
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Azure
        uses: azure/login@v2
        with:
            client-id: '8bca0021-2e37-410f-8161-ddfc8d986831'
            tenant-id: '72f988bf-86f1-41af-91ab-2d7cd011db47'
            subscription-id: '944e3b93-5fd0-47ba-9293-40c851d7d36f'

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.REGISTRY }}
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Generate build provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
